CREATE SCHEMA IF NOT EXISTS TEST AUTHORIZATION SA;

CREATE SEQUENCE IF NOT EXISTS TEST.CATEGORY_SEQ MINVALUE 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS TEST.PRODUCT_SEQ MINVALUE 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS TEST.TOY_SEQ MINVALUE 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS TEST.MEDICINE_SEQ MINVALUE 1 INCREMENT BY 1;


CREATE TABLE IF NOT EXISTS TEST.CATEGORY
(
  CATEGORY_ID   INTEGER PRIMARY KEY,
  NAME VARCHAR(255)
);


CREATE TABLE IF NOT EXISTS TEST.PRODUCT
(
  PRODUCT_ID          INTEGER PRIMARY KEY,
  NAME        VARCHAR(255),
  CATEGORY_ID INT,
  FOREIGN KEY (CATEGORY_ID) REFERENCES TEST.CATEGORY (CATEGORY_ID)
); 

CREATE TABLE IF NOT EXISTS TEST.TOY
(
  TOY_ID          INTEGER PRIMARY KEY,
  NAME        VARCHAR(255),
  CATEGORY_ID INT,
  FOREIGN KEY (CATEGORY_ID) REFERENCES TEST.CATEGORY (CATEGORY_ID)
); 

CREATE TABLE IF NOT EXISTS TEST.MEDICINE
(
  MEDICINE_ID          INTEGER PRIMARY KEY,
  NAME        VARCHAR(255),
  CATEGORY_ID INT,
  FOREIGN KEY (CATEGORY_ID) REFERENCES TEST.CATEGORY (CATEGORY_ID)
);